---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fieldobs-datasense
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fieldobs-ecsites
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fieldobs-radobs
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fieldobs-satobs
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fieldobs-smhi
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fieldobs-update-ui-geojsons
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: fmi-meteo-downloader
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hy-rclone
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: icos-downloader
  namespace: field-observatory
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hatakkaj-receiver
  namespace: field-observatory
