{{ $labels := include "field-observatory.labels" . | indent 2 }}
{{- range $serviceaccounts := $.Values.serviceaccounts }}
{{- if $serviceaccounts.enabled }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ required "Specify the name for the service account!" $serviceaccounts.name }}
  namespace: {{ required "Specify the namespace!" $.Values.namespace }}
{{- end }}
{{- end }}
